# Generated by Django 4.0.4 on 2022-05-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('U', 'Utensílio'), ('M', 'Móvel'), ('L', 'Lazer'), ('O', 'Outros')], default='O', max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
    ]
