# Generated by Django 3.2.10 on 2022-03-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], max_length=17),
        ),
    ]
