# Generated by Django 3.2.10 on 2022-03-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_clientemodel_slug'),
        ('pedidos', '0002_alter_pedidomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.produtomodel'),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='var_cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel', verbose_name='Cliente'),
        ),
    ]
