# Generated by Django 3.2.10 on 2022-03-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20220308_0646'),
        ('pedidos', '0004_auto_20220305_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='var_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cliente.clientemodel', verbose_name='Cliente'),
        ),
    ]
