# Generated by Django 3.2.10 on 2022-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidomodel_var_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='categoria',
            field=models.CharField(choices=[('U', 'Utensílio'), ('M', 'Móvel'), ('L', 'Lazer'), ('O', 'Outros')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
