# Generated by Django 3.2.10 on 2022-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20220503_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='approved_by_admin',
            field=models.BooleanField(default=True),
        ),
    ]
