# Generated by Django 4.0.4 on 2022-05-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedidos', '0007_pedidomodel_approved_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtomodel'),
        ),
        migrations.DeleteModel(
            name='produtoModel',
        ),
    ]
