# Generated by Django 3.2.10 on 2022-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
