# Generated by Django 3.2.10 on 2022-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_clientemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
