# Generated by Django 3.2.10 on 2022-03-08 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0005_clientemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
